# Generated by Django 5.1 on 2024-08-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=9823434543, max_length=10),
            preserve_default=False,
        ),
    ]
